apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-tracer-app3
  labels:
    app: jaeger-tracer-app3
spec:
  replicas: {{ .Values.app3.replicaCount }}
  selector:
    matchLabels:
      app: jaeger-tracer-app3
  template:
    metadata: 
      labels:
        app: jaeger-tracer-app3
    spec:
     containers:
     - image: {{ .Values.app3.image.repository }}:{{ .Values.app3.image.tag }}
       name: jaeger-tracer-app3
       ports:
       - containerPort: {{ .Values.app3.image.port }}
       env:
       - name: JAEGER_AGENT_HOST
         value: {{ .Values.jaegerAgentHost }}
       - name: IP
         value: app3-service.default.svc.cluster.local
       - name: REDIS_HOST
         value: redis-service.default.svc.cluster.local
