{{- if .Values.enableJaegerAllInOne }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-tracing
spec:
  selector:
    matchLabels:
      app: jaeger-tracing
  template:
    metadata:
      labels:
        app: jaeger-tracing
        jaeger-infra: jaeger-pod
    spec:
      containers:
       - image: jaegertracing/all-in-one:1.8
         name: jaeger-all-in-one
         ports:
           - containerPort: 5775
             protocol: UDP
           - containerPort: 6831
             protocol: UDP
           - containerPort: 6832
             protocol: UDP
           - containerPort: 5778
             protocol: TCP
           - containerPort: 16686
             protocol: TCP
           - containerPort: 9411
             protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger-tracing
    jaeger-infra: jaeger-service
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    jaeger-infra: jaeger-pod
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
 name: jaeger-collector
 labels:
   app: jaeger
   jaeger-infra: collector-service
spec:
 ports:
 - name: jaeger-collector-tchannel
   port: 14267
   protocol: TCP
   targetPort: 14267
 - name: jaeger-collector-http
   port: 14268
   protocol: TCP
   targetPort: 14268
 - name: jaeger-collector-zipkin
   port: 9411
   protocol: TCP
   targetPort: 9411
 selector:
   jaeger-infra: jaeger-pod
 type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
 name: jaeger-agent
 labels:
   app: jaeger
   jaeger-infra: agent-service
spec:
 ports:
 - name: agent-zipkin-thrift
   port: 5775
   protocol: UDP
   targetPort: 5775
 - name: agent-compact
   port: 6831
   protocol: UDP
   targetPort: 6831
 - name: agent-binary
   port: 6832
   protocol: UDP
   targetPort: 6832
 - name: agent-configs
   port: 5778
   protocol: TCP
   targetPort: 5778
 clusterIP: None
 selector:
   jaeger-infra: jaeger-pod
---
apiVersion: v1
kind: Service
metadata:
 name: zipkin
 labels:
   app: jaeger
   jaeger-infra: zipkin-service
spec:
 ports:
 - name: jaeger-collector-zipkin
   port: 9411
   protocol: TCP
   targetPort: 9411
 clusterIP: None
 selector:
   jaeger-infra: jaeger-pod

{{ end }}